### PR TITLE
Icons added

### PR DESCRIPTION
**Pull request by nogtini**

### CODE REVIEW

**Comment by devinivy** [comment]
Wait, there's no way we can keep fenced code blocks that look reasonable on github and on web? CC @tjwebb

**Comment by nogtini** [comment]
There is, that's why we'll always have a master branch seperate from our GH-pages branch. GH-pages branch uses Jekyll, which uses kramdown, which expects {% highlight js %} vs ```js

**Comment by devinivy** [comment]
Ahh, gotchya :)

**Comment by nogtini** [comment]
You do raise a good point in that we'll want them to be isomorphic, so we'll probably have to run a hook at some point that looks for ```js and converts to {% highlight %} when merging from master, and vice versa.

Going to investigate a better way to do this... there's gotta be a way that gh-pages can support GFM even when it uses kramdown..

There is also the issue of "front-matter" which github pages requires as a signal for the markdown documents to be processed... this too does not exist (and should not) in the markdown files in the master branch, and will have to be added when merging into gh-pages in order to be processed and displayed.

**Comment by nogtini** [comment]
Alright, so I found a solution for the fenced code blocks. I'm going to implement Redcarpet which can be configured with default extensions enabling fenced code blocks and proper GFM table parsing.

After this, the only change in content between master and gh-pages branches should be the addition of the YAML front-matter at the top of each file we wish to convert. This is something we can tackle once we decide on a work flow for keeping gh-pages up to date with master.

**Pull request merged**
